language: python
python:
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
  - pip install codecov

install:
  - poetry install -v

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)